# Generated by Django 4.1.2 on 2023-02-08 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuestas', '0002_pregunta_createdat_pregunta_updateat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respuesta',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Pregunta',
            new_name='Question',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answers', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Question'},
        ),
    ]
