# Generated by Django 4.1.2 on 2023-02-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_rename_respuesta_answer_rename_pregunta_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='fecha',
        ),
    ]
