# Generated by Django 4.1.2 on 2023-03-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0002_anuncio_anunciohasredes_categoria_redessociales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='redes',
        ),
        migrations.AddField(
            model_name='redessociales',
            name='anuncio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.anuncio'), # type: ignore
            preserve_default=False,
        ),
    ]
