# Generated by Django 4.1.2 on 2023-03-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0004_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='entrega_cuentas',
            new_name='metodos_entrega',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='capacitacion',
        ),
    ]
