# Generated by Django 4.1.2 on 2023-03-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0005_rename_entrega_cuentas_anuncio_metodos_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='persona_id',
        ),
    ]
