# Generated by Django 4.1.2 on 2023-03-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0006_remove_anuncio_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='metodos_entrega',
            field=models.CharField(choices=[('1', 'Domicilio'), ('2', 'Recogido en la tienda'), ('3', 'Envio por correo'), ('4', 'Contra Entrega'), ('5', 'Domicilio y Recogido en la tienda'), ('6', 'Recogido en la tienda y Envio por correo')], max_length=30),
        ),
    ]
