# Generated by Django 4.1.2 on 2023-03-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0007_alter_anuncio_metodos_entrega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposcapacitaciones',
            options={'verbose_name': 'Capacitacion', 'verbose_name_plural': 'Capacitacitaciones'},
        ),
        migrations.RemoveField(
            model_name='tiposcapacitaciones',
            name='tipo',
        ),
    ]
