# Generated by Django 4.1.2 on 2023-04-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0008_alter_tiposcapacitaciones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='formas_pago',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='metodos_entrega',
            field=models.CharField(max_length=300),
        ),
    ]
