# Generated by Django 4.1.2 on 2023-04-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0009_alter_anuncio_formas_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='tipo_capacitacion',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo_capacitacion',
            field=models.ManyToManyField(to='classified_advertisements.tiposcapacitaciones'),
        ),
    ]
