# Generated by Django 4.1.2 on 2023-04-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0010_remove_anuncio_tipo_capacitacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redessociales',
            name='anuncio',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='redes',
            field=models.ManyToManyField(related_name='redes_store', to='classified_advertisements.redessociales'),
        ),
        migrations.DeleteModel(
            name='AnuncioHasRedes',
        ),
    ]
