# Generated by Django 4.1.2 on 2023-04-28 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0011_remove_redessociales_anuncio_anuncio_redes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='subCategori',
            new_name='subCategoria',
        ),
    ]
