# Generated by Django 4.1.2 on 2023-04-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0013_rename_ciudad_anuncio_corregimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoria',
            old_name='categoriId',
            new_name='categoriaId',
        ),
    ]
