# Generated by Django 4.1.2 on 2023-05-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0015_alter_anuncio_redes_alter_anuncio_tipo_capacitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redessociales',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiposcapacitaciones',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
