# Generated by Django 4.1.2 on 2023-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0016_anuncio_visible_categoria_visible_producto_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='redessociales',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tiposcapacitaciones',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
