# Generated by Django 4.1.2 on 2023-05-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0019_alter_anuncio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='formas_pago',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='metodos_entrega',
            field=models.CharField(max_length=900),
        ),
    ]
