# Generated by Django 4.1.2 on 2023-05-31 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classified_advertisements', '0020_alter_anuncio_formas_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.anuncio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('emprendimiento', 'usuario')},
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
