# Generated by Django 4.1.2 on 2023-05-31 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classified_advertisements', '0021_votoanuncio_delete_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votoanuncio',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='votoanuncio',
            unique_together={('emprendimiento', 'user')},
        ),
    ]
