# Generated by Django 4.1.2 on 2023-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0022_rename_usuario_votoanuncio_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/%Y/'),
        ),
    ]
