# Generated by Django 4.1.2 on 2023-06-04 22:15

import apps.validators.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0023_alter_anuncio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/%Y/', validators=[apps.validators.index.validate_image, apps.validators.index.extension_type]),
        ),
    ]
