# Generated by Django 4.1.2 on 2023-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_document_types_usercreate_document_types_userupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_types',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='genders',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='headquarters',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='programs',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resources_roles',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
