# Generated by Django 4.1.2 on 2024-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_alter_document_types_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
