# Generated by Django 4.1.2 on 2024-01-19 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_alter_persons_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2024, 1, 19)),
        ),
    ]
