# Generated by Django 4.1.2 on 2023-05-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_module', '0003_faculties_name_headquarters_name_programs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='roles',
            field=models.ManyToManyField(related_name='resources_roles', through='auth_module.Resources_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='resources_roles',
            name='rolesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resouces_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='user_roles', through='auth_module.User_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user_roles',
            name='rolesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
