# Generated by Django 4.1.2 on 2023-05-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_module', '0005_document_types_visible_faculties_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='roles',
            field=models.ManyToManyField(db_index=True, related_name='resources_roles', through='auth_module.Resources_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(db_index=True, related_name='user_roles', through='auth_module.User_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
