# Generated by Django 4.1.2 on 2023-05-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0006_alter_resources_roles_alter_user_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='User_roles',
        ),
    ]
