# Generated by Django 4.1.2 on 2023-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_module', '0007_remove_user_roles_delete_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(db_index=True, related_name='user_roles', to='auth.group'),
        ),
    ]
