# Generated by Django 4.1.2 on 2023-05-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0008_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_module.document_types'),
        ),
    ]
