# Generated by Django 4.1.2 on 2023-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0009_alter_persons_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
