# Generated by Django 4.1.2 on 2023-12-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0013_persons_program'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
