# Generated by Django 4.1.2 on 2022-11-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_roles',
            unique_together={('userId', 'rolesId')},
        ),
    ]
