# Generated by Django 4.1.2 on 2022-11-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_resources_id_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='id_padre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
