# Generated by Django 4.1.2 on 2023-02-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_alter_persons_address_alter_persons_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
