# Generated by Django 4.1.2 on 2023-02-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0003_anexo_createdat_anexo_updateat_anexo_usercreate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateField(auto_now=True),
        ),
    ]
