# Generated by Django 4.1.2 on 2023-02-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0006_alter_pqrs_tipopqrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='titulo',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
