# Generated by Django 4.1.2 on 2023-04-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0008_respuesta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='anexo',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Anexo',
        ),
    ]
