# Generated by Django 4.1.2 on 2023-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0009_alter_respuesta_anexo_delete_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='static/files/pqrs/'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='static/files/respuesta/'),
        ),
    ]
