# Generated by Django 4.1.2 on 2023-04-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0010_pqrs_anexo_alter_pqrs_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='status',
            field=models.CharField(choices=[('FN', 'Finalizada'), ('AC', 'Activa'), ('PD', 'Pendiente')], default='AC', max_length=10),
        ),
    ]
