# Generated by Django 4.1.2 on 2023-05-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0011_pqrs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='status',
            field=models.CharField(choices=[('FN', 'Finalizada'), ('AC', 'Activa'), ('EP', 'En espera')], default='AC', max_length=10),
        ),
    ]
