# Generated by Django 4.1.2 on 2023-05-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0012_alter_pqrs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipopqrs',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
