# Generated by Django 4.1.2 on 2023-05-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0013_asignacion_visible_pqrs_visible_respuesta_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tipopqrs',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
