# Generated by Django 4.1.2 on 2023-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0014_alter_asignacion_visible_alter_pqrs_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='pqrs/%Y/'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='pqrs/%Y/respuesta/'),
        ),
    ]
