# Generated by Django 4.1.2 on 2023-06-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0015_alter_pqrs_anexo_alter_respuesta_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
