# Generated by Django 4.1.2 on 2023-06-04 22:15

import apps.validators.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0016_alter_respuesta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='pqrs/%Y/', validators=[apps.validators.index.validate_image, apps.validators.index.extension_type]),
        ),
    ]
