# Generated by Django 4.1.2 on 2023-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='hora',
            field=models.CharField(default='4:00 PM', max_length=10),
            preserve_default=False,
        ),
    ]
