# Generated by Django 4.1.2 on 2023-04-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_faculties_programs_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='headquarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.headquarters'),
            preserve_default=False,
        ),
    ]
