# Generated by Django 4.1.2 on 2023-04-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_faculties_headquarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headquarters',
            name='userCreate',
        ),
        migrations.RemoveField(
            model_name='headquarters',
            name='userUpdate',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='userCreate',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='userUpdate',
        ),
        migrations.DeleteModel(
            name='Faculties',
        ),
        migrations.DeleteModel(
            name='Headquarters',
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
