# Generated by Django 4.1.2 on 2023-04-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_remove_headquarters_usercreate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='responsable',
            field=models.CharField(max_length=256),
        ),
    ]
