# Generated by Django 4.1.2 on 2023-04-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_eventos_fecha_alter_eventos_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
