# Generated by Django 4.1.2 on 2023-05-02 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0009_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='user',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='user',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
