# Generated by Django 4.1.2 on 2023-05-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventosarea',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subareaeventos',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
