# Generated by Django 4.1.2 on 2023-05-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_asistencia_visible_eventos_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
    ]
