# Generated by Django 4.1.2 on 2023-05-26 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0013_asistencia_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='user',
            field=models.ManyToManyField(related_name='evento_inscripcion', to=settings.AUTH_USER_MODEL),
        ),
    ]
