# Generated by Django 4.1.2 on 2023-05-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_alter_inscripcion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.eventos'),
        ),
    ]
