# Generated by Django 4.1.2 on 2023-05-26 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0015_alter_asistencia_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
