# Generated by Django 4.1.2 on 2023-05-29 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_alter_inscripcion_evento_alter_inscripcion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 5, 29)),
        ),
    ]
