# Generated by Django 4.1.2 on 2023-05-31 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_alter_eventos_objectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 5, 31)),
        ),
    ]
