# Generated by Django 4.1.2 on 2023-06-28 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_alter_eventos_fecha_alter_asistencia_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 6, 28)),
        ),
    ]
