# Generated by Django 4.1.2 on 2023-08-12 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_alter_eventos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asistencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 8, 12)),
        ),
    ]
