# Generated by Django 4.1.2 on 2023-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_asistencia_asistencia_alter_eventos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
