# Generated by Django 4.1.2 on 2023-08-12 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0034_remove_inscripcion_user_inscripcion_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('evento', 'user')},
        ),
    ]
