# Generated by Django 4.1.2 on 2023-08-16 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0012_alter_persons_identification_alter_persons_phone'),
        ('eventos', '0036_alter_eventos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='dirigido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_module.programs'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
    ]
