# Generated by Django 4.1.2 on 2023-12-27 16:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='anuncio',
            managers=[
                ('objects_subCategory', django.db.models.manager.Manager()),
            ],
        ),
    ]
