# Generated by Django 4.1.2 on 2023-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0002_alter_anuncio_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='redessociales',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiposcapacitaciones',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
