# Generated by Django 4.1.2 on 2023-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_eventos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventosarea',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subareaeventos',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
