# Generated by Django 4.1.2 on 2024-01-17 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_asistencia_createdat_alter_eventos_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 1, 17)),
        ),
    ]
