<<<<<<< HEAD
# Generated by Django 4.1.2 on 2023-03-24 21:29
=======
# Generated by Django 4.1.2 on 2023-02-05 16:11
>>>>>>> d88e9d6c7916f48e9ff67d1f9c4c6efd47899345

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('nombre_emprendimiento', models.CharField(max_length=256)),
                ('descripción', models.CharField(max_length=300)),
                ('telefono_emprendimiento', models.CharField(max_length=11)),
                ('correo_emprendimiento', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('entrega_cuentas', models.CharField(choices=[('1', 'Domicilio'), ('2', 'Recogido en la tienda'), ('3', 'Envio por correo'), ('4', 'Domicilio y Recogido en la tienda'), ('5', 'Recogido en la tienda y Envio por correo')], max_length=30)),
                ('formas_pago', models.CharField(choices=[('1', 'Tranferencia'), ('2', 'Efectivo'), ('3', 'Contra Entrega'), ('4', 'Tranferencia y Efectivo'), ('5', 'Tranferencia y Contra Entrega')], max_length=30)),
                ('capacitacion', models.CharField(choices=[('si', 'SI'), ('no', 'NO')], max_length=20)),
                ('persona_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='TiposCapacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> d88e9d6c7916f48e9ff67d1f9c4c6efd47899345
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('categoriId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.categoria')),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
<<<<<<< HEAD
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> d88e9d6c7916f48e9ff67d1f9c4c6efd47899345
            ],
            options={
                'verbose_name': 'SubCategoria',
                'verbose_name_plural': 'SubCategorias',
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Seccions',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='seccionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.seccion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='userCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
>>>>>>> d88e9d6c7916f48e9ff67d1f9c4c6efd47899345
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
<<<<<<< HEAD
                ('link', models.CharField(max_length=500)),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
=======
                ('datos', models.CharField(max_length=256)),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subCategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.subcategoria')),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
>>>>>>> d88e9d6c7916f48e9ff67d1f9c4c6efd47899345
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnuncioHasRedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('tipo', models.CharField(max_length=500)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.anuncio')),
                ('redes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.redessociales')),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='redes',
            field=models.ManyToManyField(through='classified_advertisements.AnuncioHasRedes', to='classified_advertisements.redessociales'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='subCategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.subcategoria'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo_capacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.tiposcapacitaciones'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='userCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='userUpdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
