# Generated by Django 4.1.2 on 2023-03-25 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subcategoria',
            managers=[
                ('subCategory', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoriId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='classified_advertisements.categoria'),
        ),
    ]
