# Generated by Django 4.1.2 on 2023-02-05 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classified_advertisements', '0002_anuncio_userupdate_categoria_userupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='persona_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
