# Generated by Django 4.1.2 on 2023-02-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0003_alter_anuncio_persona_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='subCategori',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='seccionId',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoriId',
        ),
        migrations.AddField(
            model_name='categoria',
            name='subategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.subcategoria'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.seccion'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='anuncio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.anuncio'),
        ),
    ]
