# Generated by Django 4.1.2 on 2023-02-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classified_advertisements', '0004_remove_anuncio_subcategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='subategori',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='anuncio',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='subCategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.subcategoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='seccionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.seccion'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoriId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classified_advertisements.categoria'),
        ),
    ]
