# Generated by Django 4.1.2 on 2023-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_asignacion_name_pqrs_name_respuesta_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipopqrs',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
