# Generated by Django 4.1.2 on 2023-05-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipomomento',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
