# Generated by Django 4.1.2 on 2023-06-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depende',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestas.question'),
        ),
    ]
