# Generated by Django 4.1.2 on 2023-06-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_question_depende'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='depende',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestas.answer'),
        ),
    ]
