# Generated by Django 4.1.2 on 2023-06-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0006_alter_question_depende'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='depende',
            new_name='depende_respuesta',
        ),
    ]
