# Generated by Django 4.1.2 on 2023-06-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0007_rename_depende_question_depende_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='componente',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
