# Generated by Django 4.1.2 on 2023-06-28 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuestas', '0008_question_componente_delete_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='usuario',
        ),
        migrations.AddField(
            model_name='answer',
            name='usuario',
            field=models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
