# Generated by Django 4.1.2 on 2023-06-28 20:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuestas', '0010_remove_answer_usuario_asweruser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AswerUser',
            new_name='AnswerUser',
        ),
    ]
