# Generated by Django 4.1.2 on 2023-06-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0011_rename_asweruser_answeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeruser',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestas.answer'),
        ),
    ]
