# Generated by Django 4.1.2 on 2023-06-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0012_alter_answeruser_respuesta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('pregunta_nombre', 'momento')},
        ),
    ]
