# Generated by Django 4.1.2 on 2023-06-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0013_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruser',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestas.question'),
        ),
    ]
