# Generated by Django 4.1.2 on 2023-06-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0014_answeruser_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tipo_pregunta',
            field=models.CharField(blank=True, choices=[('UN', 'unica respuesta'), ('MR', 'multiple respuesta'), ('PC', 'respuesta corta'), ('PL', 'respuesta larga')], max_length=100, null=True),
        ),
    ]
