# Generated by Django 4.1.2 on 2023-06-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0015_alter_question_tipo_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tipo_pregunta',
            field=models.CharField(blank=True, choices=[('UR', 'unica respuesta'), ('MR', 'multiple respuesta'), ('RC', 'respuesta corta'), ('RL', 'respuesta larga')], max_length=100, null=True),
        ),
    ]
