# Generated by Django 4.1.2 on 2023-06-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0016_alter_question_tipo_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tipo_pregunta',
            field=models.CharField(blank=True, choices=[('1', 'unica respuesta'), ('2', 'multiple respuesta'), ('3', 'respuesta corta'), ('4', 'respuesta larga')], max_length=100, null=True),
        ),
    ]
